### ISSUE TITLE
Added reverse geocoding service

### ISSUE THREAD

**Issue by jkerr5** [marklogic-community/marklogic-geo-data-services#1]
We have an implementation of a reverse geocoding service that we could include in the geo data services suite.

Investigate integrating this service into the geo data services baseline.

**Comment by taatuut** [comment]
FYI: Peter Kester and I worked on a reverse geocoding service as an MBO few Q ago. Maybe interesting.

**Comment by jkerr5** [comment]
> FYI: Peter Kester and I worked on a reverse geocoding service as an MBO few Q ago. Maybe interesting.

Yes, that is the implementation that we have :)

**Comment by taatuut** [comment]
Github repo at https://github.com/peetkes/ReverseGeoCoder
Discussed this a bit with James: as he says separate the service part, and add some default configurations for specific local/national/international layers/data sets.

**Comment by jkerr5** [comment]
We will not be adding this service to GDS.
