### ISSUE TITLE
ObjectIds parameter is not considered while aggregation

### ISSUE THREAD

**Issue by mitchshepherd** [marklogic-community/marklogic-geo-data-services#102]
Connector code is skipping objectIds parameter while aggregation. Hence it returns the count for all documents in a layer.

URL : /marklogic/GDeltGKG/FeatureServer/0/query?objectIds=56577%2C56576&returnCountOnly=true
Actual Result : 38765
Expected Result : 2

Copied issue from [koop-provider-marklogic](https://github.com/koopjs/koop-provider-marklogic) by [jmamanpara](https://github.com/jmamanpara) commented [on Apr 13, 2018](https://github.com/koopjs/koop-provider-marklogic/issues/65#issue-314260769)

**Comment by BillFarber** [comment]
To try this out with our current setup in the "develop" branch, you need change the ML port in default.json to 8096 and restart the node server.
The try http://localhost/marklogic/GDeltGKG/FeatureServer/0/query?objectIds=56577%2C56576&returnCountOnly=true

**Comment by BillFarber** [comment]
Rob pointed out that instead of changing default.json, you run the Node server with:
npm run start-no-auth
Then use this link to see the query:
http://localhost:8090/marklogic/GDeltGKG/FeatureServer/0/query?objectIds=56577%2C56576&returnCountOnly=true

**Comment by rjrudin** [comment]
Resolved via #118
