### ISSUE TITLE
Set useStandardizedQueries to true for all layers

### ISSUE THREAD

**Issue by mitchshepherd** [marklogic-community/marklogic-geo-data-services#103]
The layer metadata should contain useStandardizedQueries : true such that clients only send in "standard SQL" (SQL 92)

Check if this is done already though.

Copied issue from [koop-provider-marklogic](https://github.com/koopjs/koop-provider-marklogic) by [jkerr5](https://github.com/jkerr5) commented [on Mar 5, 2018](https://github.com/koopjs/koop-provider-marklogic/issues/50#issue-302394681)

**Comment by BillFarber** [comment]
https://github.com/koopjs/koop-provider-marklogic/issues/50

**Comment by rjrudin** [comment]
Closed via #134
