### ISSUE TITLE
Remove the use of the flora parser

### ISSUE THREAD

**Issue by mitchshepherd** [marklogic-community/marklogic-geo-data-services#105]
MarkLogic 9.0-4 should add a new optic function to parse a SQL where clause so the flora parser will no longer be needed. Refactor as necessary.

Copied issue from [koop-provider-marklogic](https://github.com/koopjs/koop-provider-marklogic) by [jkerr5](https://github.com/jkerr5) commented [on Nov 22, 2017](https://github.com/koopjs/koop-provider-marklogic/issues/20#issue-276259483)

___

MarkLogic 9.0-4 has been released and now supports a SQL where expression as a where clause. We can now do something like

.where(op.sqlCondition("OBJECTID IN (57011, 34484)"))
instead of using the flora sql parser.

We may still need to leverage the flora sql parser to implement https://github.com/koopjs/koop-provider-marklogic/issues/11 as that would require handling some custom SQL function.

This may also fix https://github.com/koopjs/koop-provider-marklogic/issues/7 so check once this is complete.

[jkerr5](https://github.com/jkerr5) commented [on Jan 24, 2018](https://github.com/koopjs/koop-provider-marklogic/issues/20#issuecomment-360201431)

---

Reevaluate if we can get rid of the SQL parser given the current handling of SQL where clauses in the optic API
[jkerr5](https://github.com/jkerr5) commented [3 days ago](https://github.com/koopjs/koop-provider-marklogic/issues/20#issuecomment-1384161175)

**Comment by rjrudin** [comment]
I don't believe this is possible yet per a conversation we recently had. `op.sqlCondition` does help out, but it can't handle everything yet, such as "TO_DATE".
