### ISSUE TITLE
koop-provider-marklogic example project

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/marklogic-geo-data-services#13]
Create an _example_ project to load koop-provider-marklogic with a npm install.
Link the koop-provider-marklogic to a marklogic-geo-data-services backend through a properties file.

**Comment by jkerr5** [comment]
This should also have the logic to build in disconnected mode like the old version did.

**Comment by prestonmcgowan** [comment]
We had removed the exact disconnected component, making it so that we would just make use of the normal node component or gradle component for disconnect mode. Disconnected more would therefore be a wiki page on how to use node or gradle to create a disconnected build.

Preston McGowan
Principal Consultant
MarkLogic Corporation
preston.mcgowan@marklogic.com
Cell: +1 727 278 8925
www.marklogic.com

This e-mail and any accompanying attachments are confidential. The information is intended solely for the use of the individual to whom it is addressed. Any review, disclosure, copying, distribution, or use of this e-mail communication by others is strictly prohibited. If you are not the intended recipient, please notify us immediately by returning this message to the sender and delete all copies. Thank you for your cooperation.
________________________________

**Comment by jkerr5** [comment]
@prestonmcgowan this ticket is for an _example_ project to illustrate it. I prefer that rather than a wiki page.

**Comment by jkerr5** [comment]
This is covered by the example project and the docker example as well.
