### ISSUE TITLE
Provide an example of how to test a service after deploying

### ISSUE THREAD

**Issue by jkerr5** [marklogic-community/marklogic-geo-data-services#21]
We need to show how to test to see if the service has been deployed and is providing data.

**Comment by mfgumban** [comment]
Is the idea to further expand the docs on describing how to test/invoke the services, or provide example "code" (e.g. scripts or gradle) to test?  The assumption here is the data may or may not be the provided example data, but data being used by the developer, correct?

**Comment by jkerr5** [comment]
Yes, just further expand on the docs. If a service with name "MyService" is create, how would the developer test to see if they can access it? Or show what the minimum request is to retrieve the first 10 features, for example.
