### ISSUE TITLE
Example Esri Connector project

### ISSUE THREAD

**Issue by mfgumban** [marklogic-community/marklogic-geo-data-services#32]
Use containers to setup an environment with a working Koop server (with a MarkLogic provider) and database with Geo Data Services installed.  The setup should also have sample data prepped and loaded, making the environment ready for use.

**Comment by jkerr5** [comment]
There is also some GKG data already downloaded that we use for testing: https://github.com/marklogic-community/marklogic-geo-data-services/tree/master/data/test/gkg_geojson Maybe it would be best to just have some of that in the example project too?

**Comment by mfgumban** [comment]
Agreed.  These can be added during the deployment phase.

**Comment by mfgumban** [comment]
Closing issue; changes were included in PR #36.
