### ISSUE TITLE
Improve processing of zip code sample data

### ISSUE THREAD

**Issue by mfgumban** [marklogic-community/marklogic-geo-data-services#34]
The [zip code boundary sample data](https://github.com/OpenDataDE/State-zip-code-GeoJSON) consists of numerous JSON files (19~ MB each).  Currently, they are ingested via mlcp as-is and each simply wrapped in an envelope pattern.  I have encountered instances where mlcp fails due to   "Premature EOF", which sometimes happens in resource-restrictive environments (like a container), or when ingesting via network.  The database also ends up with large-sized documents, which may impact performance(?)

Should we consider cutting these up into smaller chunks before ingest?

**Comment by jkerr5** [comment]
Yes, the goal would be to have each zip code end up as it's own GeoJSON document not to have one GeoJSON document per state with a FeatureCollection that contains all of the zip codes. I believe we would have to modify the loader logic to do this so I think this turns into a real issue and not just a question.

**Comment by mfgumban** [comment]
Closing issue; changes were included in PR #36.
