### ISSUE TITLE
Fix variance plugin so it does not build on windows

### ISSUE THREAD

**Issue by mfgumban** [marklogic-community/marklogic-geo-data-services#35]
The Vaiance Plugin section of the README states: 
> If the build is run on a Windows machine, the build and install of the native plugin will be skipped.

but it seems that it doesn't skip and will try to run `make` on Windows (10).  Do we fix deployment to align or just remove this statement from the README?

**Comment by jkerr5** [comment]
It used to skip it correctly before we moved over to GDS. We should fix it to skip the build and install of the plugin for now and address the actual build and install of the plugin on Windows if someone ever needs to install this onto a MarkLogic cluster running on Windows.

**Comment by mfgumban** [comment]
There is an ml-app-deployer property `mlPluginInstallationEnabled` that can be used to skip deploying plugins (and running make), which can be coupled with some groovy code that checks the host OS.

The move to a bundle means any custom gradle task (that Koop used to have) would not get carried over, because a bundle is nothing more than a bunch of ML file assets.

A quick fix (for now) is to instruct users to add an 'mlPluginInstallationEnabled=false` in their `gradle.properties` if they plan to deploy on Windows.  

Will keep looking if there's a way to make it automatic like before.

**Comment by mfgumban** [comment]
Investigate how to handle plugin deployment now that GDS is packaged as an ML bundle.  Also consider how this impacts deploying on DHS and whether to deploy the plugin somewhere else besides the content database.

**Comment by jkerr5** [comment]
I think this is done but we should check that this is working correctly.

**Comment by rjrudin** [comment]
This is done - the README has a note, and ml-gradle documents the property - https://github.com/marklogic-community/ml-gradle/wiki/Property-reference#plugin-properties .
