### ISSUE TITLE
Add support for geotools plugin

### ISSUE THREAD

**Issue by jkerr5** [marklogic-community/marklogic-geo-data-services#37]
Make changes required to support integration with https://github.com/marklogic-community/marklogic-geotools-plugin

**Comment by rjrudin** [comment]
@jkerr5  Do you know what else is required for this? I was able to run Geoserver locally with the geotools-plugin installed in it, and it could pull data from GDS.

**Comment by jkerr5** [comment]
I believe this is covered now so it can be closed.
