### ISSUE TITLE
How to discover which layers are available using direct ML endpoints

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/marklogic-geo-data-services#46]
There are 3 endpoints, but not sure if any of them can answer the question which layers are available for querying. I'd prefer to access them directly, rather than going through an unnecessary extra layer. It seems like docs on the ML endpoints are missing in general.

**Comment by mfgumban** [comment]
The "KoopFeatureLayer" extension can be used to get this information, e.g. 
`v1/resources/KoopFeatureLayer/rs:service=my-service-name` where `my-service-name` is the service descriptor's name in the JSON property `/info/name`.

As discussed in #47, this extension will undergo some changes to make it more general purpose.

**Comment by grtjn** [comment]
Actually, I am sending this request instead:

```
POST /v1/resources/geoQueryService
{
  params: {
    method: 'describe',
    id: 'DAMOGeo',
    layer: 'all',
    maxRecordCount: 5000
  },
  query: {}
}
```

(where `maxRecordCount` is a param that I added/implemented myself)

**Comment by grtjn** [comment]
(feel free to close)
