### ISSUE TITLE
Add feature to send in cts or structured query to geoQueryService

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/marklogic-geo-data-services#47]
It is currently only expecting sql queries, but optic api can handle cts queries equally well. It would be real convenient to be able to send additional constraints, so that what you get back and potentially want to show on some map would be in synch with search results you might be showing next to it.

**Comment by grtjn** [comment]
Bonus points to accept structured next to cts query. Will require an extra parameter called `options` which would refer to the saved search options..

**Comment by jkerr5** [comment]
A CTS query can be used as the "bounding query" for a layer but it has to be currently specified via the service descriptor. The current query parameters that are supported are defined by the Esri feature service API: https://developers.arcgis.com/rest/services-reference/query-feature-service-layer-.htm 

We could add a parameter that allows the specification of a CTS query that is _anded_ with the bounding query that is defined via the service descriptor.

What kind of client are you expecting to use to access the GDS API?

**Comment by grtjn** [comment]
To put it short: a grove app. There is no added value having an extra KOOP service running next to MarkLogic for grove, as we can make it understand the GDS services directly. The Map would be part of the search experience, so if you type in some full-text word, you'd expect both search results, and results on the map to get reduced to the relevant items. To do that you need to refresh the geo data with each search, and you'd have to send along additional filters/constraints that can be of any type, geo, non-geo, temporal, ranges, full-text terms, stemmed matches, etc.

So, it has to be dynamic, and something that is *anded* with whatever else applies would be perfect.

**Comment by mfgumban** [comment]
This could be somewhat related to this Koop [issue](https://github.com/koopjs/koop-provider-marklogic/issues/163) as well.

The 2 other rest extensions beside "geoQuery" are originally there, really, to support use with ArcGIS Pro (a Windows-only thick client).  Our add-in is designed to work similar to how a search-based app, like Grove, would:

- It relies on search options to search (v1/search), and points to render (v1/values).
- It provides a search interface typical of Grove: facets, results with snippets, etc.
- It relies on a document transform to display a document's contents as an HTML page.
- A user can then save their search as a feature layer.

We are currently working to update these rest extensions to be more "general purpose", but it will still heavily rely on the Search API.  Perhaps we should consider other clients like Grove while doing these modifications.

I am wondering though on the value of using GDS/geoQuery versus just using the Search API straight up, if the purpose is to setup a map-aware search app.  Would it be to utilize the feature layers, like what the add-in is doing right now?

**Comment by grtjn** [comment]
It sounds a bit pity to have to rebuild existing search functionality if it is already available via /v1/search. As a reminder, I have a custom geo constraint that provides a dynamic heat map, and integrates into /v1/search itself: https://github.com/grtjn/ml-google-maps-ng/blob/gh-pages/geo.xqy. Moreover, using /v1/values to pull up additional, or more details geo data has the limitation that it can only return simple values, like points. Regions would be more tricky. The benefit of the geoQueryService is that it returns geojson geometries, which can be consumed by most js map libraries as-is.

**Comment by grtjn** [comment]
To capture some of what we spoke about offline: keep in mind that ui applications would typically make multiple calls to pull in facets, results, aggregates, suggestions. It makes most sense to provide separate endpoints for those. In my current search, I use /v1/search and /v1/suggest for most of the work, and just use geoQueryService to populate the map with all relevant features for each of the layers. I didn't really need anything else.

That said, there likely is a real need for better geo heatmap support. The /v1/search support for geo heatmaps is limited, and patching it with a custom geo constraint feels clumsy.

We also spoke about the cascade of 3 detail levels:

1. cluster markers
2. center points (with links to real docs)
3. full features (complete linestrings and polygons on the map)

My app is showing 3 only, but is focused around a part of one small country.

**Comment by grtjn** [comment]
I am working on providing my changes to geoQueryService for review as a PR, but need to synch with 1.1.1 release before I can do so. My project is still running 1.1.0.

**Comment by mfgumban** [comment]
Merged in 1.2.0 release
