### ISSUE TITLE
How to configure layers to be driven by more traditional geo indexes

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/marklogic-geo-data-services#49]
Using TDE to drive feature layers is convenient and flexible, but if you'd like to use geospatial constraints to limit search results, you'll need real geospatial indexes. If you have those, could you use those to drive feature layers, rather than pointing them to sql schemas?

**Comment by jkerr5** [comment]
Can you expand on this? TDE or SPARQL queries are used to identify the properties of the features that are served and the geospatial indexes are used to limit what documents those features come from. If only using the geo indexes, how would you expect to retrieve the other attributes of the features?

**Comment by grtjn** [comment]
On second thought, I think you are right. Please ignore..
