### ISSUE TITLE
Adjustments related to DHS

### ISSUE THREAD

**Issue by mfgumban** [marklogic-community/marklogic-geo-data-services#56]
In relation to using GDS with a DHS project:

- DHS is more restrictive with security roles (see [here](https://docs.marklogic.com/datahub/security/users-and-roles.html), particularly the requirements on custom roles)
- To comply, it is recommended for the geo-* roles to inherit rest-reader/writer *privileges* instead of roles.

**Comment by mfgumban** [comment]
A side effect of going down to privileges is the loss of the `rest-extensions-user` role, which is needed to execute resource extensions.  Based on DHS rules, we can't have custom roles inherit it.  The DHS developer has to provision a user with that role manually, instead of via project deployment.

**Comment by jkerr5** [comment]
OBE
