### ISSUE TITLE
Complete service descriptor reference

### ISSUE THREAD

**Issue by mfgumban** [marklogic-community/marklogic-geo-data-services#66]
Document all currently possible variations of defining a service descriptor.

**Comment by mfgumban** [comment]
The `geometrySource` property seems like a remnant of an older implementation:
https://github.com/marklogic-community/marklogic-geo-data-services/blob/b3e434014c451235ec773ec497e4eeb95f5d254b/src/main/ml-modules/services/geoQueryService.sjs#L1018-L1025

- It only supports `xpath` as an option
- The `geometry` property is more verbose (different types, sources such as xpath or column, etc.) and is referenced by most of the extractor functions
- The above snippet is the only time `geometrySource` gets used.
- Declaring anything other than `xpath` would result in an Optic API error where the "doc" column is not found.  This is because the "doc" column is added by the extractors, and they don't use `geometrySource`.

We may want to consider dropping/deprecating this in favor of `geometry`.

**Comment by jkerr5** [comment]
I am fine with dropping it. We just need to update any tests that may use
the legacy format.

**Comment by rjrudin** [comment]
We have an internal JIRA-based effort to address this.
