### ISSUE TITLE
REFACTOR: change xdmp.trace prefixes from KOOP to GDS

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/marklogic-geo-data-services#8]
Change xdmp.trace("KOOP-
To xdmp.trace("GDS-

Document the trace events supported by this project.

**Comment by mfgumban** [comment]
Changing the prefix to "GDS" is straightforward.

Right now there's really only one (1) type of trace event: "KOOP-DEBUG".  If we want to document these events we should organize them into event types that would make sense.  One way would be to organize events by function or module -- for example:

```javascript
function getPointQuery(regions, layerModel) {
  xdmp.trace("KOOP-DEBUG", "Using the following extractor: getPointQuery");
  const pointQueries = [];

  switch(layerModel.geometry.format) {
    case "geojson" : {
      xdmp.trace("KOOP-DEBUG", "getPointQuery geometry format: geojson");

  // and so on...
```

might be changed so:
```javascript
function getPointQuery(regions, layerModel) {
  const pointQueries = [];

  switch(layerModel.geometry.format) {
    case "geojson" : {
      xdmp.trace("GDS-GETPOINTQUERY", "Geometry format: geojson");

  // and so on...
```

**Comment by jkerr5** [comment]
I think we just need one top-level trace event for troubleshooting GDS. If we find that it is too much info, we can break the event into sub-groups.

When this change is made, we should also refactor to make sure all `xdmp.trace()` calls are within a check to make sure the trace event is enabled first. This is to reduce unnecessary overhead of constructing the trace messages when tracing is not enabled. Assign a module-level boolean to the result of `xdmp.traceEnabled('GDS-DEBUG')` and wrap all the trace calls in an `if (traceEnabled)`
