### ISSUE TITLE
Add support for un-publishing layers in geoserver

### ISSUE THREAD

**Issue by tdiepenbrock** [marklogic-community/marklogic-geo-data-services#81]
Modify the geoserverService to implement an http DELETE call with the same URL parameters as the POST call.  The DELETE will un-publish the service descriptor's layers from GeoServer.

**Comment by rjrudin** [comment]
Apparently a PR was merged already, but no tests. Will leave this open until a test is added, even though this was likely "released" already.

**Comment by rjrudin** [comment]
Closing, as geoserverService has been deleted due to it being unused
