### ISSUE TITLE
add support for different join types

### ISSUE THREAD

**Issue by tdiepenbrock** [marklogic-community/marklogic-geo-data-services#85]
Add support for leftOuterJoin, innerJoin, etc. We have an implementation that has been in use already in a customer's forked repo where the optional "joinFunction" property can be in the service descriptor->layer->dataSource object:

{
...
"joinOn": {
  "left": "LEFT_COLUMN_NAME", 
  "right": "RIGHT_COLUMN_NAME"
  },
"joinFunction":"joinLeftOuter",
...
}

The value of this property may be "joinLeftOuter", "joinInner", "joinFullOuter". If this property is not present, it defaults to "joinInner" like it does now.  

NOTE:  "joinFullOuter" is only supported on MarkLogic 10.0-5 and later.  The "joinCrossProduct" function is NOT supported.

**Comment by tdiepenbrock** [comment]
Adding specific tests for joinLeftOuter and joinFullOuter, as well as tests for an invalid join function to make the failure message more understandable.  Leaving joinInner tested implicitly through several of the other ServiceDescriptorArray tests.  Also added a test to ensure we specifically fail on joinCrossProduct, since this function requires a different signature and returns a full cross product of the views involved--which tends to dramatically increase rows returned.  If we decide to implement joinCrossProduct later we'll need to update the joinCrossProduct test.

**Comment by tdiepenbrock** [comment]
After further discussions:

We will move the type of join into the joinOn property.  The type of join will be indicated by a “joinType” property, which can have legal values of “inner”, “left outer”, and “full outer”:

joinOn {
  “left”:”leftColumn”,
  “right”:”rightColumn”,
  “joinType”:[“inner” | “left outer” | “full outer"]
}

**Comment by jkerr5** [comment]
Release 1.3.4
