### ISSUE TITLE
The returnIdsOnly parameter needs to get the id column from the service descriptor

### ISSUE THREAD

**Issue by jkerr5** [marklogic-community/marklogic-geo-data-services#94]
Right now, the column for ids is hardcoded to be "OBJECTID": https://github.com/marklogic-community/marklogic-geo-data-services/blob/01e0f246454f6276683e5234a325a836c7c08410/src/main/ml-modules/services/geoQueryService.sjs#L656

It is also hardcoded here: https://github.com/marklogic-community/marklogic-geo-data-services/blob/01e0f246454f6276683e5234a325a836c7c08410/src/main/ml-modules/services/geoQueryService.sjs#L692

The code should lookup what the id column is in the service/layer descriptor from the `idField`. If the `idField` is not set, default to "OBJECTID".

**Comment by rjrudin** [comment]
Resolved via #125
