### ISSUE TITLE
Use /tde prefix when loading templates

### ISSUE THREAD

**Issue by mitchshepherd** [marklogic-community/marklogic-geo-data-services#97]
New versions of ml-gradle don't require TDE templates to use the "tdex" extension. https://github.com/marklogic-community/ml-gradle/wiki/Loading-schemas

As of version 2.7.0, TDE rulesets no longer need to have a "tdex" or "tdej" suffix. Instead, any document with a URI starting with "/tde" will be put into the "http://marklogic.com/xdmp/tde" collection.

It would be preferable for TDE's to be stored with their native xml or json file extension in the "templates" directory, and insert them into the schema's DB under /tde/{fsConfig}/.

Copied issue from [koop-provider-marklogic](https://github.com/koopjs/koop-provider-marklogic) by [aclavio](https://github.com/aclavio) commented [on Mar 28, 2019](https://github.com/koopjs/koop-provider-marklogic/issues/152#issue-426665700)

**Comment by rjrudin** [comment]
This is fine as-is, it only impacts our tests, and the TDE's are being loaded correctly.
