### ISSUE TITLE
Add the ability to get geometry from a column but don't return the column as a feature field

### ISSUE THREAD

**Issue by mitchshepherd** [marklogic-community/marklogic-geo-data-services#98]
The current implementation requires the column to be selected from the view in order to be in scope for the Optic plan but there is no way to select it only to extract the geometry an not include it in the feature properties.

Copied issue from [koop-provider-marklogic](https://github.com/koopjs/koop-provider-marklogic) by [jkerr5](https://github.com/jkerr5) commented [on Nov 22, 2018](https://github.com/koopjs/koop-provider-marklogic/issues/138#issue-383573818)

**Comment by jkerr5** [comment]
This would be a nice update to add in 1.4.0.

**Comment by rjrudin** [comment]
Managing this internally in JIRA, will look to instead address this need via Optic Geo in GDS 2.0.
