### ISSUE TITLE
Change the KoopFeatureLayer.sjs service to use a layer template

### ISSUE THREAD

**Issue by mitchshepherd** [marklogic-community/marklogic-geo-data-services#99]
Specify a layer "template" that the service uses to create all other layers. This allows the service to be more configuration-driven.

Copied issue from [koop-provider-marklogic](https://github.com/koopjs/koop-provider-marklogic) by [jkerr5](https://github.com/jkerr5) commented [on Aug 23, 2018](https://github.com/koopjs/koop-provider-marklogic/issues/101#issue-353268690)

**Comment by rjrudin** [comment]
The sands seem to have shifted here - this module no longer exists, so this seems obsolete.
